# Text preprocessing
glove_vectors_path: data/GloVe/vectors.txt # don't change
raw_data_path: data/bbc_toi_yahoo_stats_feats.csv # dont't change

# Clickstream data Generation
clickstream_data_path: data/generated/clickstream.csv # don't change
total_users: 100
train_data_path: data/generated/train_clickstream.csv # don't change
test_data_path: data/generated/test_clickstream.csv # don't change
test_fraction: 0.1

# Data config
clustered_vectorized_data_path: data/common/bbc_toi_yahoo_news_clustered_vectored.csv # don't change

# NeuMF config
pretrained: False
evaluate: True
epochs: 5
user_dimensions: 64
learning_rate: 0.0001
comb_type: concat
pretrained_weights_path: weights/
batch_size: 32
