# Clickstream data Generation
clickstream_data_path: data/generated/clickstream.csv # don't change
use_cached_clickstream: True
total_users: 1000
total_articles: 8000
train_data_path: data/generated/train_clickstream.csv # don't change
test_data_path: data/generated/test_clickstream.csv # don't change
test_fraction: 0.2

# Data config
clustered_vectorized_data_path: data/common/bbc_toi_yahoo_news_clustered_vectored.csv # don't change

# NeuMF config
evaluate: True
pretrained: False
epochs: 2
user_dimensions: 100
learning_rate: 0.0001
comb_type: concat
pretrained_weights_path: weights/model_hybrid_api.h5 # don't change
batch_size: 128